export const fr = {
    weather: {
        summary: {
            hot: 'très chaud',
            warm: 'chaud',
            mild: 'doux',
            cool: 'frais',
            cold: 'froid',
            freezing: 'très froid',
            base: "Il fait {desc} ({temp}°C ressenti).",
            rain: 'Prévoyez protection contre la pluie.',
            coldLayer: 'Habillez-vous chaudement.',
            hotLayer: 'Légèreté recommandée.',
        },
    },
    outfit: {
        reasons: {
            coldProtection: 'Protection contre le froid',
            sunProtection: 'Protection soleil',
            niceTemp: 'Température agréable',
            summerHeat: 'Chaleur estivale',
            lightProtection: 'Protection légère',
            isolation: 'Couche isolante',
            outerLayer: 'Couche extérieure protectrice',
            maxAir: 'Aération maximale',
            breathable: 'Confort respirant',
            dailyComfort: 'Confort quotidien',
            thermalIsolation: 'Isolation thermique',
            rain: 'Précipitations probables',
            wind: 'Protection vent/cou',
        },
        items: {
            beanie: 'Bonnet',
            cap: 'Casquette légère',
            none: 'Aucun',
            tshirtShort: 'T-shirt manches courtes',
            tshirtLong: 'T-shirt manches longues',
            sweater: 'Pull ou sweat',
            coat: 'Manteau chaud',
            jacket: 'Veste légère',
            shorts: 'Short ou jupe légère',
            pantsLight: 'Pantalon léger',
            pants: 'Pantalon',
            sandals: 'Sandales ou chaussures légères',
            sneakers: 'Baskets ou chaussures fermées',
            shoes: 'Chaussures fermées + chaussettes',
            umbrella: 'Parapluie ou imperméable',
            scarf: 'Écharpe',
        },
    },
    ui: {
        confidence: {
            label: 'Confiance',
            low: 'Faible',
            medium: 'Moyenne',
            high: 'Élevée',
        },
    },
};
